name = "spinogambinoapp-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinoapp.de"
HMAC_KEY = "5bbbd3518f206b1f5b93209e03d6f7fa3b3508596d5d8149ce85167172554e93"
COOKIE_NAME = "p5x"
PLAY_PATH = "start-now"
BUTTON_ID = "p783bda336d0c00dc62ee8cc6cb071030"
GATE_SALT = "abba7aef6f646014"
